sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t swpril/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swpril/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: docker
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-287840991022'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
